<?php

/**
 * Copyright (c) 2026 Online Tech Support, LLC
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

declare(strict_types=1);

namespace App\Controller;

use App\Auth\Auth;
use App\Auth\RateLimiter;
use App\Auth\Session;
use App\Http\Request;
use App\Http\Response;
use App\Model\AuditLog;
use App\Model\Chatbot;
use App\Model\Conversation;
use App\Model\Document;
use App\Model\Lead;
use App\Model\Message;
use App\Model\QuickAnswer;
use App\Model\Admin;
use App\Model\UserPermission;
use App\Service\OpenAIClient;
use App\Service\RetrievalEngine;
use App\Util\PromptScanner;
use JsonException;

/**
 * ChatController — handles chatbot query endpoints.
 *
 * Two entry points:
 *   1. Authenticated test chat (POST /chatbots/{id}/chat) — for the dashboard preview panel
 *   2. Public chat (POST /api/public/chat) — for the embeddable widget, authenticated by widget_token
 */
class ChatController
{
    /**
     * POST /chatbots/{id}/chat — Authenticated test chat for the dashboard.
     *
     * Expects JSON body: { "message": "..." }
     * Creates or reuses a test conversation for the admin user.
     */
    public function testChat(Request $req, Response $res, array $params): void
    {
        $user = Auth::requireAuth();
        Auth::requirePermission($user, 'test_chat');
        $adminId = (int) $user['admin_id'];
        $chatbotId = (int) ($params['id'] ?? 0);

        if ($chatbotId <= 0) {
            $res->json(['error' => 'Invalid chatbot ID'], 400)->send();
            return;
        }

        // Verify chatbot belongs to this admin account
        $chatbot = Chatbot::find($chatbotId);
        Auth::requireSameAdmin($user, $chatbot);

        $body = json_decode(file_get_contents('php://input'), true);
        $userMessage = trim($body['message'] ?? '');

        if ($userMessage === '') {
            $res->json(['error' => 'Message is required'], 400)->send();
            return;
        }

        // Use a stable test session ID tied to the user
        $visitorSessionId = 'test_' . $user['id'] . '_' . $chatbotId;

        try {
            $result = $this->processQuery($adminId, $chatbot, $visitorSessionId, $userMessage, $_SERVER['REMOTE_ADDR'] ?? null, userId: (int) $user['id']);
            $res->json($result)->send();
        } catch (\Throwable $e) {
            $res->json(['error' => $e->getMessage()], 500)->send();
        }
    }

    /**
     * POST /api/public/chat — Public chat endpoint for the embeddable widget.
     *
     * Expects JSON body: { "widget_token": "...", "message": "...", "session_id": "..." }
     * session_id is a UUID generated by the widget and stored in localStorage.
     */
    public function publicChat(Request $req, Response $res): void
    {
        // CORS preflight: allow from any origin (actual origin check happens below after chatbot lookup)
        header('Access-Control-Allow-Methods: POST, OPTIONS');
        header('Access-Control-Allow-Headers: Content-Type');

        if ($req->method === 'OPTIONS') {
            header('Access-Control-Allow-Origin: *');
            $res->setStatus(204)->send();
            return;
        }

        $body = json_decode(file_get_contents('php://input'), true);
        $widgetToken = trim($body['widget_token'] ?? '');
        $userMessage = trim($body['message'] ?? '');
        $visitorSessionId = trim($body['session_id'] ?? '');

        if ($widgetToken === '' || $userMessage === '' || $visitorSessionId === '') {
            $res->json(['error' => 'widget_token, message, and session_id are required'], 400)->send();
            return;
        }

        // Look up chatbot by widget token
        $chatbot = Chatbot::findByWidgetToken($widgetToken);
        if ($chatbot === null) {
            $res->json(['error' => 'Invalid or inactive chatbot'], 404)->send();
            return;
        }

        // ── CORS origin validation ───────────────────────────────────────
        $origin = $_SERVER['HTTP_ORIGIN'] ?? '';
        $host = $_SERVER['HTTP_HOST'] ?? '';
        $originAllowed = self::isOriginAllowed($origin, $chatbot['allowed_domains'] ?? null, $host);
        if (!$originAllowed) {
            $res->json(['error' => 'Origin not allowed'], 403)->send();
            return;
        }
        if ($origin !== '') {
            header('Access-Control-Allow-Origin: ' . $origin);
            header('Vary: Origin');
        }
        // Same-origin requests (no Origin header) do not need CORS headers.

        $permUserId = (int) ($chatbot['created_by'] ?? $chatbot['admin_id']);
        $adminId = (int) $chatbot['admin_id'];

        // Account active check — disabled users cannot serve widget requests
        $owner = \App\Model\User::find($permUserId);
        if (!$owner || empty($owner['is_active'])) {
            $res->json(['error' => 'Account disabled'], 403)->send();
            return;
        }

        // Endpoint toggle — widget owner can disable the widget
        if (!UserPermission::has($permUserId, 'widget_chat')) {
            $res->json(['error' => 'Chat widget is disabled for this account'], 403)->send();
            return;
        }

        // Check the user who owns this chatbot has API keys configured
        $keyOwnerId = (int) ($chatbot['created_by'] ?? $chatbot['admin_id']);
        $keys = Admin::getApiKeys($keyOwnerId);
        if (empty($keys['openai_api_key'])) {
            $res->json(['error' => 'Chatbot is not configured (missing API keys)'], 503)->send();
            return;
        }

        try {
            $result = $this->processQuery($adminId, $chatbot, $visitorSessionId, $userMessage, $_SERVER['REMOTE_ADDR'] ?? null, userId: $keyOwnerId);
            $res->json($result)->send();
        } catch (\Throwable $e) {
            $res->json(['error' => 'An error occurred processing your request'], 500)->send();
        }
    }

    /**
     * GET /api/public/quick-answers — Return active quick answers for a widget chatbot.
     *
     * Expects query param: widget_token=...
     * Returns JSON array of { trigger, answer } objects.
     */
    public function publicQuickAnswers(Request $req, Response $res): void
    {
        // CORS preflight: allow from any origin (actual origin check happens below after chatbot lookup)
        header('Access-Control-Allow-Methods: GET, OPTIONS');
        header('Access-Control-Allow-Headers: Content-Type');

        if ($req->method === 'OPTIONS') {
            header('Access-Control-Allow-Origin: *');
            $res->setStatus(204)->send();
            return;
        }

        $widgetToken = trim($req->get('widget_token') ?? '');

        if ($widgetToken === '') {
            $res->json(['error' => 'widget_token is required'], 400)->send();
            return;
        }

        $chatbot = Chatbot::findByWidgetToken($widgetToken);
        if ($chatbot === null) {
            $res->json(['error' => 'Invalid or inactive chatbot'], 404)->send();
            return;
        }

        // ── CORS origin validation ───────────────────────────────────────
        $origin = $_SERVER['HTTP_ORIGIN'] ?? '';
        $host = $_SERVER['HTTP_HOST'] ?? '';
        $originAllowed = self::isOriginAllowed($origin, $chatbot['allowed_domains'] ?? null, $host);
        if (!$originAllowed) {
            $res->json(['error' => 'Origin not allowed'], 403)->send();
            return;
        }
        if ($origin !== '') {
            header('Access-Control-Allow-Origin: ' . $origin);
            header('Vary: Origin');
        }
        // Same-origin requests (no Origin header) do not need CORS headers.

        $permUserId = (int) ($chatbot['created_by'] ?? $chatbot['admin_id']);
        $adminId = (int) $chatbot['admin_id'];
        $chatbotId = (int) $chatbot['id'];

        // Account active check — disabled users cannot serve widget requests
        $owner = \App\Model\User::find($permUserId);
        if (!$owner || empty($owner['is_active'])) {
            $res->json(['error' => 'Account disabled'], 403)->send();
            return;
        }

        // Endpoint toggle — widget owner can disable quick answers
        if (!UserPermission::has($permUserId, 'widget_quick_answers')) {
            $res->json(['error' => 'Quick answers are disabled for this account'], 403)->send();
            return;
        }

        $quickAnswers = QuickAnswer::findActiveByChatbot($adminId, $chatbotId);

        // Return only the fields the widget needs
        $result = array_map(fn($qa) => [
            'trigger' => $qa['trigger'],
            'answer'  => $qa['answer'],
        ], $quickAnswers);

        $res->json($result)->send();
    }

    /**
     * POST /api/public/rate — Submit a 1-5 star rating for a conversation.
     *
     * Expects JSON body: { "widget_token": "...", "session_id": "...", "rating": "5" }
     * rating is sanitized via preg_replace leaving only digits, then clamped to 1-5.
     */
    public function publicRate(Request $req, Response $res): void
    {
        // CORS preflight
        header('Access-Control-Allow-Methods: POST, OPTIONS');
        header('Access-Control-Allow-Headers: Content-Type');

        if ($req->method === 'OPTIONS') {
            header('Access-Control-Allow-Origin: *');
            $res->setStatus(204)->send();
            return;
        }

        $body = json_decode(file_get_contents('php://input'), true);
        $widgetToken   = trim($body['widget_token'] ?? '');
        $visitorSessionId = trim($body['session_id'] ?? '');
        $rawRating     = trim((string) ($body['rating'] ?? ''));

        if ($widgetToken === '' || $visitorSessionId === '' || $rawRating === '') {
            $res->json(['error' => 'widget_token, session_id, and rating are required'], 400)->send();
            return;
        }

        // ── Per-IP rate limit ──
        $ip = $req->clientIp();
        if (!RateLimiter::check($ip, 10, 300, 'rating:')) {
            $res->json(['error' => 'Too many rating attempts. Try again later.'], 429)->send();
            return;
        }

        // Look up chatbot
        $chatbot = Chatbot::findByWidgetToken($widgetToken);
        if ($chatbot === null) {
            $res->json(['error' => 'Invalid or inactive chatbot'], 404)->send();
            return;
        }

        // ── CORS origin validation ──
        $origin = $_SERVER['HTTP_ORIGIN'] ?? '';
        $host = $_SERVER['HTTP_HOST'] ?? '';
        $originAllowed = self::isOriginAllowed($origin, $chatbot['allowed_domains'] ?? null, $host);
        if (!$originAllowed) {
            $res->json(['error' => 'Origin not allowed'], 403)->send();
            return;
        }
        if ($origin !== '') {
            header('Access-Control-Allow-Origin: ' . $origin);
            header('Vary: Origin');
        }

        $adminId   = (int) $chatbot['admin_id'];
        $chatbotId = (int) $chatbot['id'];

        // Find the conversation for this visitor
        $conversation = Conversation::findBySession($chatbotId, $visitorSessionId);
        if ($conversation === null) {
            $res->json(['error' => 'Conversation not found'], 404)->send();
            return;
        }

        // ── Once-only: reject if already rated ──
        if ($conversation['rating'] !== null) {
            RateLimiter::record($ip, 'rating:');
            $res->json(['error' => 'Conversation already rated'], 409)->send();
            return;
        }

        // Sanitize and store rating — the model uses preg_replace to strip non-digits
        $saved = Conversation::rate((int) $conversation['id'], $rawRating);
        if (!$saved) {
            $res->json(['error' => 'Invalid rating — must be 1-5'], 422)->send();
            return;
        }

        RateLimiter::clear($ip, 'rating:');
        $res->json(['success' => true])->send();
    }

    /**
     * Core RAG query processing — shared by both test and public endpoints.
     *
     * @param  int    $adminId
     * @param  array  $chatbot
     * @param  string $visitorSessionId
     * @param  string $userMessage
     * @param  string|null $visitorIp
     * @return array  ['reply' => string, 'conversation_id' => int, 'source' => string, 'chunks_used' => int]
     */
    private function processQuery(int $adminId, array $chatbot, string $visitorSessionId, string $userMessage, ?string $visitorIp, ?int $userId = null): array
    {
        $chatbotId = (int) $chatbot['id'];
        $systemPrompt = $chatbot['system_prompt'] ?? '';
        $modelConfig = !empty($chatbot['model_config']) ? json_decode($chatbot['model_config'], true) : [];

        // Get API keys — prefer the authenticated user's keys, fall back to admin keys
        $keyOwnerId = $userId ?? $adminId;
        $keys = Admin::getApiKeys($keyOwnerId);
        $openAiKey = $keys['openai_api_key'] ?? '';

        if (empty($openAiKey)) {
            throw new \RuntimeException('OpenAI API key not configured for this account');
        }

        $openai = new OpenAIClient($openAiKey);

        // 1. Find or create conversation
        $conversation = Conversation::findOrCreate($adminId, $chatbotId, $visitorSessionId, $visitorIp);
        $conversationId = (int) $conversation['id'];

        // 2. Store the user's message
        $startTime = (int) (microtime(true) * 1000);
        Message::create($adminId, $chatbotId, $conversationId, $visitorSessionId, 'user', $userMessage);

        // 3. Check QuickAnswers first (trigger-based exact match)
        $quickMatch = QuickAnswer::matchMessage($adminId, $chatbotId, $userMessage);
        if ($quickMatch !== null) {
            $reply = $quickMatch['answer'];
            $endTime = (int) (microtime(true) * 1000);
            $responseTimeMs = $endTime - $startTime;
            $tokensUsed = (int) ((strlen($userMessage) + strlen($reply)) / 4);
            Message::create(
                $adminId, $chatbotId, $conversationId, $visitorSessionId,
                'assistant', $reply, $tokensUsed, $responseTimeMs, 'quick_answer'
            );
            Conversation::touch($conversationId);
            return [
                'reply'           => $reply,
                'conversation_id' => $conversationId,
                'source'          => 'quick_answer',
                'chunks_used'     => 0,
            ];
        }

        // ── Guardrails (silent abuse prevention) ────────────────────────────
        // These checks silently log violations and respond with a polite canned
        // reply so the visitor never sees an error or filter message.

        // Polite canned response used by all guardrails — sounds like an AI assistant
        // politely declining rather than a system error.
        $POLITE_BLOCKED_REPLY = "I'm sorry, I'm not able to help with that request. Is there something else I can assist you with?";

        // Guardrail #2 — Max message length
        if (!empty($chatbot['max_message_length'])) {
            $maxLen = (int) $chatbot['max_message_length'];
            if (mb_strlen($userMessage) > $maxLen) {
                AuditLog::log(
                    $adminId, $userId, 'abuse_guardrail', 'chatbot', $chatbotId,
                    null,
                    ['guardrail' => 'max_message_length', 'length' => mb_strlen($userMessage), 'limit' => $maxLen, 'conversation_id' => $conversationId]
                );
                $reply = $POLITE_BLOCKED_REPLY;
                $endTime = (int) (microtime(true) * 1000);
                $responseTimeMs = $endTime - $startTime;
                $tokensUsed = 0;
                Message::create($adminId, $chatbotId, $conversationId, $visitorSessionId, 'assistant', $reply, $tokensUsed, $responseTimeMs, 'blocked');
                Conversation::touch($conversationId);
                return ['reply' => $reply, 'conversation_id' => $conversationId, 'source' => 'blocked', 'chunks_used' => 0];
            }
        }

        // Guardrail #3 — Max messages per conversation
        if (!empty($chatbot['max_messages_per_conversation'])) {
            $maxMsgs = (int) $chatbot['max_messages_per_conversation'];
            $messageCount = (int) ($conversation['message_count'] ?? 0);
            if ($messageCount >= $maxMsgs) {
                AuditLog::log(
                    $adminId, $userId, 'abuse_guardrail', 'chatbot', $chatbotId,
                    null,
                    ['guardrail' => 'max_messages_per_conversation', 'message_count' => $messageCount, 'limit' => $maxMsgs, 'conversation_id' => $conversationId]
                );
                $reply = $POLITE_BLOCKED_REPLY;
                $endTime = (int) (microtime(true) * 1000);
                $responseTimeMs = $endTime - $startTime;
                $tokensUsed = 0;
                Message::create($adminId, $chatbotId, $conversationId, $visitorSessionId, 'assistant', $reply, $tokensUsed, $responseTimeMs, 'blocked');
                Conversation::touch($conversationId);
                return ['reply' => $reply, 'conversation_id' => $conversationId, 'source' => 'blocked', 'chunks_used' => 0];
            }
        }

        // Guardrail #4 — Prompt injection / jailbreak detection (universal, no config needed)
        $injectionCategory = PromptScanner::scan($userMessage);
        if ($injectionCategory !== null) {
            AuditLog::log(
                $adminId, $userId, 'abuse_guardrail', 'chatbot', $chatbotId,
                null,
                ['guardrail' => 'prompt_injection', 'category' => $injectionCategory, 'message_preview' => mb_substr($userMessage, 0, 200), 'conversation_id' => $conversationId]
            );
            $reply = $POLITE_BLOCKED_REPLY;
            $endTime = (int) (microtime(true) * 1000);
            $responseTimeMs = $endTime - $startTime;
            $tokensUsed = 0;
            Message::create($adminId, $chatbotId, $conversationId, $visitorSessionId, 'assistant', $reply, $tokensUsed, $responseTimeMs, 'blocked');
            Conversation::touch($conversationId);
            return ['reply' => $reply, 'conversation_id' => $conversationId, 'source' => 'blocked', 'chunks_used' => 0];
        }

        // ── Cost & abuse protection (rate limit, token budget) ──────────────
        // These checks run before any OpenAI API call so we don't pay for
        // requests we're about to reject.

        if (!empty($chatbot['rate_limit_per_session'])) {
            $recentCount = Conversation::countRecentBySession(
                $chatbotId,
                $visitorSessionId,
                1  // messages in the last 1 minute
            );
            if ($recentCount >= (int) $chatbot['rate_limit_per_session']) {
                throw new \RuntimeException(
                    'You\'re sending messages too quickly. Please wait a moment and try again.'
                );
            }
        }

        if (!empty($chatbot['daily_token_budget'])) {
            $tokensToday = Conversation::sumTokensUsedToday($chatbotId);
            if ($tokensToday >= (int) $chatbot['daily_token_budget']) {
                throw new \RuntimeException(
                    'This chatbot has reached its daily message budget. Please try again tomorrow.'
                );
            }
        }

        // 5. Use the RetrievalEngine to get relevant context (supports multiple strategies)
        $retrievalEngine = new \App\Service\RetrievalEngine($openai);
        $retrievalResult = $retrievalEngine->retrieve($adminId, $chatbot, $userMessage);

        $chunksUsed = $retrievalResult->getChunksUsed();
        $ragContext = $retrievalResult->getContext();

        // 6. Get recent conversation history (for context window)
        $recentMessages = Message::getRecentByConversation($conversationId, 10);

        // 7. Assemble the messages array for OpenAI
        $messages = [];

        // System prompt
        $systemMessage = !empty($systemPrompt)
            ? $systemPrompt
            : 'You are a helpful customer support assistant. Answer questions using the information available to you. '
            . 'If you don\'t know the answer, say so politely and naturally — just say "I don\'t have that information on hand" '
            . 'or "I\'m not sure about that one." Never mention "context", "documents", "provided information", or any internal mechanics. '
            . 'Be concise, accurate, and conversational, like a knowledgeable support rep.';

        if (!empty($ragContext)) {
            $systemMessage .= "\n\n--- RELEVANT DOCUMENT CONTEXT ---\n" . $ragContext . "\n--- END CONTEXT ---\n\n"
                . 'Use the above information to answer the user\'s question naturally — '
                . 'do NOT mention that you are referring to documents, context, or any internal data source. '
                . 'Simply answer as if you already know the information. '
                . 'If the information does not cover their question, say so in a natural way '
                . '(e.g. "I don\'t have that information available") without referencing the context system.';
        }

        // Inject lead capture instructions if enabled and not yet captured
        if (!empty($chatbot['lead_capture_enabled'])) {
            $existingLead = Lead::findByConversation($conversationId);
            if ($existingLead === null) {
                $systemMessage .= "\n\n--- LEAD CAPTURE INSTRUCTION ---\n"
                    . 'You are a customer support assistant who also collects visitor contact information '
                    . 'for human follow-up. You have two trigger patterns for asking:\n'
                    . "\n"
                    . 'PATTERN 1 — Proactive early ask: After a brief greeting or once the visitor has stated '
                    . 'what they need help with, ask for their full name, email address, and phone number '
                    . 'together in a single natural message, framed as what you need in order to help them '
                    . 'or follow up (e.g. "Happy to help with that — could I grab your name, email, and a '
                    . 'phone number so I can follow up if needed?").\n'
                    . "\n"
                    . 'PATTERN 2 — Off-scope / hands-on request: Whenever a visitor asks you to do something '
                    . 'you cannot do yourself — make changes to their website, write code, design graphics, '
                    . 'optimize their site, or anything that requires hands-on work by a person — or whenever '
                    . 'their question is not answered by the information available to you: IMMEDIATELY say '
                    . 'that you will have someone from the company reach out to help them, and ask for their '
                    . 'full name, email, and phone number together in a single natural message. Frame it as '
                    . '"I can\'t make those changes directly, but I\'ll have someone from our team reach out — '
                    . 'could I get your name, email, and a phone number so they can follow up?"\n'
                    . "\n"
                    . 'RULES:\n'
                    . '- Ask for all three fields in one message rather than spacing them out.\n'
                    . '- If the visitor only provides some details, politely ask for the rest once.\n'
                    . '- If the visitor declines, drop it and continue helping them with what you can.\n'
                    . '- Do not be pushy — if they ignore the request, move on.'
                    . "\n--- END LEAD CAPTURE INSTRUCTION ---\n";
            }
        }


        $messages[] = ['role' => 'system', 'content' => $systemMessage];

        // Conversation history (skip system messages, include user/assistant turns)
        foreach ($recentMessages as $msg) {
            if (in_array($msg['role'], ['user', 'assistant'], true)) {
                $messages[] = ['role' => $msg['role'], 'content' => $msg['content']];
            }
        }

        // 8. Call OpenAI Chat Completions
        $temperature = (float) ($modelConfig['temperature'] ?? 0.7);
        $maxTokens = (int) ($modelConfig['max_tokens'] ?? 1024);
        $model = $modelConfig['model'] ?? 'gpt-4o-mini';

        $reply = $openai->chatCompletion($messages, [
            'model'       => $model,
            'temperature' => $temperature,
            'max_tokens'  => $maxTokens,
        ]);

        // 9. Calculate response time
        $endTime = (int) (microtime(true) * 1000);
        $responseTimeMs = $endTime - $startTime;

        // 10. Store the assistant's response
        $source = $chunksUsed > 0 ? 'rag' : 'llm_only';
        // Rough token estimate (4 chars ≈ 1 token)
        $tokensUsed = (int) ((strlen($userMessage) + strlen($reply)) / 4);
        Message::create(
            $adminId, $chatbotId, $conversationId, $visitorSessionId,
            'assistant', $reply, $tokensUsed, $responseTimeMs, $source
        );

        // 11. Touch the conversation (update message_count, last_message_at)
        Conversation::touch($conversationId);

        // 12. Lead capture — extract name/email/phone (any of them) and conversation summary
        if (!empty($chatbot['lead_capture_enabled'])) {
            $existingLead = Lead::findByConversation($conversationId);
            $allMessages = Message::findByConversation($conversationId);
            $extracted = $this->extractLeadInfo($allMessages, $openai, $modelConfig);

            if ($existingLead === null) {
                // No lead yet — create one if at least one contact field was provided
                if (!empty($extracted['name']) || !empty($extracted['email']) || !empty($extracted['phone'])) {
                    Lead::createLead([
                        'admin_id'          => $adminId,
                        'chatbot_id'         => $chatbotId,
                        'conversation_id'    => $conversationId,
                        'visitor_session_id' => $visitorSessionId,
                        'name'               => $extracted['name'],
                        'email'              => $extracted['email'],
                        'phone'              => $extracted['phone'],
                        'summary'            => $extracted['summary'],
                        'captured_at'        => date('Y-m-d H:i:s'),
                    ]);
                }
            } else {
                // Lead exists — update fields if more info surfaced, and refresh summary
                $updates = [];
                if (!empty($extracted['name']) && empty($existingLead['name'])) {
                    $updates['name'] = $extracted['name'];
                }
                if (!empty($extracted['email']) && empty($existingLead['email'])) {
                    $updates['email'] = $extracted['email'];
                }
                if (!empty($extracted['phone']) && empty($existingLead['phone'])) {
                    $updates['phone'] = $extracted['phone'];
                }
                if (!empty($extracted['summary'])) {
                    $updates['summary'] = $extracted['summary'];
                }
                if (!empty($updates)) {
                    Lead::update($existingLead['id'], $updates);
                }
            }
        }

        return [
            'reply'           => $reply,
            'conversation_id' => $conversationId,
            'source'          => $source,
            'chunks_used'     => $chunksUsed,
        ];
    }

    /**
     * Extract name, email, and phone from user messages using an LLM call.
     *
     * Uses OpenAI chat completions with JSON mode for reliable structured extraction.
     * Silently returns nulls on any failure (API error, bad JSON, etc.).
     *
     * @param  array         $messages    Message rows from the database
     * @param  OpenAIClient  $openai      OpenAI client instance
     * @param  array         $modelConfig Chatbot model configuration (model, temperature, max_tokens)
     * @return array{name: ?string, email: ?string, phone: ?string}
     */
    private function extractLeadInfo(array $messages, OpenAIClient $openai, array $modelConfig): array
    {
        $allUserText = '';
        foreach ($messages as $msg) {
            if ($msg['role'] === 'user') {
                $allUserText .= "\n" . ($msg['content'] ?? '');
            }
        }
        $allUserText = trim($allUserText);

        if ($allUserText === '') {
            return ['name' => null, 'email' => null, 'phone' => null, 'summary' => null];
        }

        $systemMessage = 'You are a data extraction assistant. Extract the person\'s full name, email address, '
            . 'and phone number from the conversation text below. '
            . 'Also write a brief 1-2 sentence summary of what the visitor is contacting about based on the entire conversation. '
            . 'Return ONLY valid JSON in this exact structure (use null for missing fields): '
            . '{"name": "Full Name or null", "email": "email@example.com or null", "phone": "phone number or null", "summary": "1-2 sentence summary of the conversation or null"}';

        try {
            $reply = $openai->chatCompletion([
                ['role' => 'system', 'content' => $systemMessage],
                ['role' => 'user', 'content' => $allUserText],
            ], [
                'model'           => $modelConfig['model'] ?? 'gpt-4o-mini',
                'temperature'     => (float) ($modelConfig['temperature'] ?? 0.7),
                'max_tokens'      => (int) ($modelConfig['max_tokens'] ?? 1024),
                'response_format' => ['type' => 'json_object'],
            ]);

            $data = json_decode($reply, true, 512, JSON_THROW_ON_ERROR);

            return [
                'name'  => !empty($data['name']) ? trim((string) $data['name']) : null,
                'email' => !empty($data['email']) ? trim((string) $data['email']) : null,
                'phone' => !empty($data['phone']) ? trim((string) $data['phone']) : null,
                'summary' => !empty($data['summary']) ? trim((string) $data['summary']) : null,
            ];
        } catch (\Throwable $e) {
            // API failure or bad JSON — silently return nulls
        }

        return ['name' => null, 'email' => null, 'phone' => null, 'summary' => null];
    }
    
    /**
     * Check if the request Origin matches one of the allowed domains.
     *
     * Accepts an Origin header in the form `https://example.com` or `https://example.com:8443`,
     * normalizes it by stripping default ports (80 for http, 443 for https), then compares
     * against the saved allow list (which is normalized the same way during save).
     * Supports wildcard port syntax (example.com:*), exact match, and port-specific match.
     */
    private static function isOriginAllowed(string $origin, ?string $allowedDomains, string $host = ''): bool
    {
        // No allow list configured = allow all (backward compatible)
        if ($allowedDomains === null || trim($allowedDomains) === '') {
            return true;
        }

        // Determine which host:port to check against the allow list.
        // Cross-origin requests send an Origin header; same-origin requests do not,
        // so we fall back to the Host header for those.
        if ($origin !== '') {
            // Cross-origin — parse the Origin header
            if (preg_match('#^https?://#i', $origin)) {
                $parts = parse_url($origin);
                $originHost = strtolower($parts['host'] ?? '');
                $originPort = $parts['port'] ?? null;
                $originScheme = strtolower($parts['scheme'] ?? '');

                if ($originHost === '') {
                    return false;
                }

                // Strip default ports (80 for http, 443 for https)
                if ($originPort !== null) {
                    if (($originScheme === 'http' && $originPort === 80) || ($originScheme === 'https' && $originPort === 443)) {
                        $originPort = null;
                    }
                }

                $normalizedOrigin = $originHost . ($originPort !== null ? ':' . $originPort : '');
            } else {
                // Malformed origin — use raw value
                $normalizedOrigin = strtolower($origin);
                $originHost = $normalizedOrigin;
            }
        } else {
            // Same-origin request — use Host header for validation
            $host = strtolower($host);
            $hostParts = explode(':', $host);
            $originHost = $hostParts[0];
            $normalizedOrigin = $host;
        }

        $allowed = explode("\n", $allowedDomains);

        foreach ($allowed as $domain) {
            $domain = trim($domain);
            if ($domain === '') {
                continue;
            }

            // Support wildcard port: example.com:* matches example.com:3000
            if (str_ends_with($domain, ':*')) {
                $hostPrefix = substr($domain, 0, -2);
                if (strcasecmp($originHost, $hostPrefix) === 0) {
                    return true;
                }
            } elseif (str_contains($domain, ':')) {
                // Exact host:port match — port is explicit in the saved domain
                if (strcasecmp($normalizedOrigin, $domain) === 0) {
                    return true;
                }
            } else {
                // Bare domain without port — match any port on that host
                $originHostOnly = preg_replace('/:\d+$/', '', $normalizedOrigin);
                if (strcasecmp($originHostOnly, $domain) === 0) {
                    return true;
                }
            }
        }

        return false;
    }
}
