--
-- PostgreSQL database dump
--

-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SELECT pg_catalog.set_config('search_path', '', false);

--
-- Name: chatbot_schema; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS chatbot_schema;

--
-- Name: current_admin_id(); Type: FUNCTION; Schema: chatbot_schema; Owner: -
--

CREATE OR REPLACE FUNCTION chatbot_schema.current_admin_id() RETURNS integer
    LANGUAGE sql STABLE
    AS $$
    SELECT NULLIF(current_setting('app.admin_id', true), '')::INTEGER;
$$;

--
-- Name: FUNCTION current_admin_id(); Type: COMMENT; Schema: chatbot_schema; Owner: -
--

COMMENT ON FUNCTION chatbot_schema.current_admin_id() IS 'Reads app.admin_id from session settings. NULL means bypass RLS (public widget / installer).';

--
-- Name: audit_logs; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.audit_logs (
    id bigint NOT NULL,
    admin_id integer,
    user_id integer,
    action character varying(64) NOT NULL,
    entity_type character varying(64) DEFAULT NULL::character varying,
    entity_id integer,
    old_value jsonb,
    new_value jsonb,
    ip_address character varying(45) DEFAULT NULL::character varying,
    user_agent text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: chatbot_schema; Owner: -
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'audit_logs_id_seq' AND relnamespace = 'chatbot_schema'::regnamespace) THEN
ALTER TABLE chatbot_schema.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chatbot_schema.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);  END IF;
END $$;

--
-- Name: chat_stats; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.chat_stats (
    id integer NOT NULL,
    admin_id integer NOT NULL,
    chatbot_id integer NOT NULL,
    date date NOT NULL,
    total_conversations integer DEFAULT 0 NOT NULL,
    total_messages integer DEFAULT 0 NOT NULL,
    unique_visitors integer DEFAULT 0 NOT NULL,
    avg_response_time_ms integer,
    total_tokens integer DEFAULT 0 NOT NULL,
    answered_by_quick integer DEFAULT 0 NOT NULL,
    answered_by_custom integer DEFAULT 0 NOT NULL,
    answered_by_rag integer DEFAULT 0 NOT NULL,
    unanswered_count integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--
-- Name: chat_stats_id_seq; Type: SEQUENCE; Schema: chatbot_schema; Owner: -
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'chat_stats_id_seq' AND relnamespace = 'chatbot_schema'::regnamespace) THEN
ALTER TABLE chatbot_schema.chat_stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chatbot_schema.chat_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);  END IF;
END $$;

--
-- Name: chatbots; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.chatbots (
    id integer NOT NULL,
    admin_id integer NOT NULL,
    created_by integer NOT NULL,
    name character varying(255) NOT NULL,
    industry character varying(100) DEFAULT NULL::character varying,
    system_prompt text,
    model_config jsonb,
    styling jsonb,
    status character varying(10) DEFAULT 'active'::character varying NOT NULL,
    lead_capture_enabled smallint DEFAULT 0 NOT NULL,
    daily_token_budget bigint,
    rate_limit_per_session integer,
    allowed_domains text,
    widget_token character varying(64) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    max_message_length integer,
    max_messages_per_conversation integer,
    retrieval_strategy character varying(20) DEFAULT 'traditional_rag'::character varying NOT NULL,
    CONSTRAINT chatbots_retrieval_strategy_check CHECK (((retrieval_strategy)::text = ANY ((ARRAY['traditional_rag'::character varying, 'page_index'::character varying])::text[]))),
    CONSTRAINT chatbots_status_check CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'paused'::character varying])::text[])))
);

--
-- Name: chatbots_id_seq; Type: SEQUENCE; Schema: chatbot_schema; Owner: -
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'chatbots_id_seq' AND relnamespace = 'chatbot_schema'::regnamespace) THEN
ALTER TABLE chatbot_schema.chatbots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chatbot_schema.chatbots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);  END IF;
END $$;

--
-- Name: conversations; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.conversations (
    id integer NOT NULL,
    admin_id integer NOT NULL,
    chatbot_id integer NOT NULL,
    visitor_session_id character varying(128) NOT NULL,
    visitor_ip character varying(45) DEFAULT NULL::character varying,
    message_count integer DEFAULT 0 NOT NULL,
    first_message_at timestamp without time zone,
    last_message_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--
-- Name: conversations_id_seq; Type: SEQUENCE; Schema: chatbot_schema; Owner: -
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'conversations_id_seq' AND relnamespace = 'chatbot_schema'::regnamespace) THEN
ALTER TABLE chatbot_schema.conversations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chatbot_schema.conversations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);  END IF;
END $$;

--
-- Name: document_chunks; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.document_chunks (
    id integer NOT NULL,
    admin_id integer NOT NULL,
    chatbot_id integer NOT NULL,
    document_id integer NOT NULL,
    chunk_index integer NOT NULL,
    chunk_text text NOT NULL,
    embedding chatbot_schema.vector(1536) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--
-- Name: document_chunks_id_seq; Type: SEQUENCE; Schema: chatbot_schema; Owner: -
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'document_chunks_id_seq' AND relnamespace = 'chatbot_schema'::regnamespace) THEN
ALTER TABLE chatbot_schema.document_chunks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chatbot_schema.document_chunks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);  END IF;
END $$;

--
-- Name: document_page_index; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.document_page_index (
    id integer NOT NULL,
    admin_id integer NOT NULL,
    chatbot_id integer NOT NULL,
    document_id integer NOT NULL,
    parent_id integer,
    node_type character varying(20) DEFAULT 'section'::character varying NOT NULL,
    heading character varying(512) DEFAULT NULL::character varying,
    heading_level smallint,
    content text,
    node_order integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT document_page_index_heading_level_check CHECK (((heading_level IS NULL) OR ((heading_level >= 1) AND (heading_level <= 6)))),
    CONSTRAINT document_page_index_node_type_check CHECK (((node_type)::text = ANY ((ARRAY['root'::character varying, 'section'::character varying, 'subsection'::character varying, 'leaf'::character varying])::text[])))
);

--
-- Name: document_page_index_id_seq; Type: SEQUENCE; Schema: chatbot_schema; Owner: -
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'document_page_index_id_seq' AND relnamespace = 'chatbot_schema'::regnamespace) THEN
ALTER TABLE chatbot_schema.document_page_index ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chatbot_schema.document_page_index_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);  END IF;
END $$;

--
-- Name: document_strategies; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.document_strategies (
    id integer NOT NULL,
    admin_id integer NOT NULL,
    chatbot_id integer NOT NULL,
    document_id integer NOT NULL,
    original_name character varying(255) NOT NULL,
    strategy character varying(20) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT document_strategies_strategy_check CHECK (((strategy)::text = ANY ((ARRAY['traditional_rag'::character varying, 'page_index'::character varying])::text[])))
);

--
-- Name: document_strategies_id_seq; Type: SEQUENCE; Schema: chatbot_schema; Owner: -
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'document_strategies_id_seq' AND relnamespace = 'chatbot_schema'::regnamespace) THEN
ALTER TABLE chatbot_schema.document_strategies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chatbot_schema.document_strategies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);  END IF;
END $$;

--
-- Name: documents; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.documents (
    id integer NOT NULL,
    admin_id integer NOT NULL,
    chatbot_id integer NOT NULL,
    filename character varying(255) NOT NULL,
    original_name character varying(255) NOT NULL,
    mime_type character varying(127) DEFAULT NULL::character varying,
    file_path character varying(512) DEFAULT NULL::character varying,
    file_size integer,
    status character varying(20) DEFAULT 'uploaded'::character varying NOT NULL,
    error_message text,
    llamacloud_job_id character varying(255) DEFAULT NULL::character varying,
    llamacloud_status character varying(20) DEFAULT NULL::character varying,
    parsed_text text,
    chunk_count integer,
    uploaded_by integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT documents_llamacloud_status_check CHECK (((llamacloud_status IS NULL) OR ((llamacloud_status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying, 'parsed'::character varying, 'failed'::character varying])::text[])))),
    CONSTRAINT documents_status_check CHECK (((status)::text = ANY ((ARRAY['uploaded'::character varying, 'parsing'::character varying, 'parsed'::character varying, 'chunking'::character varying, 'embedding'::character varying, 'indexed'::character varying, 'failed'::character varying])::text[])))
);

--
-- Name: documents_id_seq; Type: SEQUENCE; Schema: chatbot_schema; Owner: -
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'documents_id_seq' AND relnamespace = 'chatbot_schema'::regnamespace) THEN
ALTER TABLE chatbot_schema.documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chatbot_schema.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);  END IF;
END $$;
--
-- Name: leads; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.leads (
    id integer NOT NULL,
    admin_id integer NOT NULL,
    chatbot_id integer NOT NULL,
    conversation_id integer,
    visitor_session_id character varying(255) DEFAULT NULL::character varying,
    name character varying(255) DEFAULT NULL::character varying,
    email character varying(255) DEFAULT NULL::character varying,
    phone character varying(50) DEFAULT NULL::character varying,
    summary text,
    captured_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--
-- Name: leads_id_seq; Type: SEQUENCE; Schema: chatbot_schema; Owner: -
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'leads_id_seq' AND relnamespace = 'chatbot_schema'::regnamespace) THEN
ALTER TABLE chatbot_schema.leads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chatbot_schema.leads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);  END IF;
END $$;

--
-- Name: magic_links; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.magic_links (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    admin_id integer NOT NULL,
    token character varying(64) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    used_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--
-- Name: magic_links_id_seq; Type: SEQUENCE; Schema: chatbot_schema; Owner: -
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'magic_links_id_seq' AND relnamespace = 'chatbot_schema'::regnamespace) THEN
ALTER TABLE chatbot_schema.magic_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chatbot_schema.magic_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);  END IF;
END $$;

--
-- Name: messages; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.messages (
    id integer NOT NULL,
    admin_id integer NOT NULL,
    chatbot_id integer NOT NULL,
    conversation_id integer NOT NULL,
    visitor_session_id character varying(128) NOT NULL,
    role character varying(10) NOT NULL,
    content text NOT NULL,
    tokens_used integer,
    response_time_ms integer,
    source character varying(20) DEFAULT NULL::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT messages_role_check CHECK (((role)::text = ANY ((ARRAY['user'::character varying, 'assistant'::character varying, 'system'::character varying])::text[]))),
    CONSTRAINT messages_source_check CHECK (((source IS NULL) OR ((source)::text = ANY (ARRAY['quick_answer'::text, 'rag'::text, 'llm_only'::text, 'blocked'::text]))))
);

--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: chatbot_schema; Owner: -
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'messages_id_seq' AND relnamespace = 'chatbot_schema'::regnamespace) THEN
ALTER TABLE chatbot_schema.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chatbot_schema.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);  END IF;
END $$;

--
-- Name: password_resets; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.password_resets (
    email character varying(255) NOT NULL,
    token character varying(64) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    used smallint DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--
-- Name: platform_settings; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.platform_settings (
    key character varying(64) NOT NULL,
    value text
);

--
-- Name: quick_answers; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.quick_answers (
    id integer NOT NULL,
    admin_id integer NOT NULL,
    chatbot_id integer NOT NULL,
    trigger character varying(500) NOT NULL,
    answer text NOT NULL,
    priority integer DEFAULT 0 NOT NULL,
    is_active smallint DEFAULT 1 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--
-- Name: quick_answers_id_seq; Type: SEQUENCE; Schema: chatbot_schema; Owner: -
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'quick_answers_id_seq' AND relnamespace = 'chatbot_schema'::regnamespace) THEN
ALTER TABLE chatbot_schema.quick_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chatbot_schema.quick_answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);  END IF;
END $$;

--
-- Name: rate_limits; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.rate_limits (
    id bigint NOT NULL,
    key character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--
-- Name: rate_limits_id_seq; Type: SEQUENCE; Schema: chatbot_schema; Owner: -
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'rate_limits_id_seq' AND relnamespace = 'chatbot_schema'::regnamespace) THEN
ALTER TABLE chatbot_schema.rate_limits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chatbot_schema.rate_limits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);  END IF;
END $$;

--
-- Name: sessions; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.sessions (
    id character varying(128) NOT NULL,
    user_id integer,
    admin_id integer,
    ip_address character varying(45) DEFAULT NULL::character varying,
    user_agent text,
    payload text NOT NULL,
    last_activity integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--
-- Name: user_permissions; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.user_permissions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    permission character varying(64) NOT NULL,
    enabled smallint DEFAULT 1 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--
-- Name: user_permissions_id_seq; Type: SEQUENCE; Schema: chatbot_schema; Owner: -
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'user_permissions_id_seq' AND relnamespace = 'chatbot_schema'::regnamespace) THEN
ALTER TABLE chatbot_schema.user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chatbot_schema.user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);  END IF;
END $$;

--
-- Name: users; Type: TABLE; Schema: chatbot_schema; Owner: -
--

CREATE TABLE IF NOT EXISTS chatbot_schema.users (
    id integer NOT NULL,
    admin_id integer NOT NULL,
    name character varying(255) NOT NULL,
    company_name character varying(255) DEFAULT NULL::character varying,
    brand_name character varying(255) DEFAULT 'Chatbot Assistant'::character varying NOT NULL,
    slug character varying(255) DEFAULT NULL::character varying,
    is_active smallint DEFAULT 1 NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(10) DEFAULT 'user'::character varying NOT NULL,
    email_verified_at timestamp without time zone,
    email_verify_token character varying(64) DEFAULT NULL::character varying,
    mfa_secret character varying(255) DEFAULT NULL::character varying,
    mfa_enabled smallint DEFAULT 0 NOT NULL,
    mfa_recovery_codes text,
    openai_api_key character varying(255) DEFAULT NULL::character varying,
    llamacloud_api_key character varying(255) DEFAULT NULL::character varying,
    is_locked smallint DEFAULT 0 NOT NULL,
    locked_until timestamp without time zone,
    failed_attempts integer DEFAULT 0 NOT NULL,
    last_login_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['admin'::character varying, 'user'::character varying])::text[])))
);

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: chatbot_schema; Owner: -
--

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'users_id_seq' AND relnamespace = 'chatbot_schema'::regnamespace) THEN
ALTER TABLE chatbot_schema.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chatbot_schema.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);  END IF;
END $$;

--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);

--
-- Name: chat_stats chat_stats_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.chat_stats
    ADD CONSTRAINT chat_stats_pkey PRIMARY KEY (id);

--
-- Name: chatbots chatbots_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.chatbots
    ADD CONSTRAINT chatbots_pkey PRIMARY KEY (id);

--
-- Name: conversations conversations_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.conversations
    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);

--
-- Name: document_chunks document_chunks_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.document_chunks
    ADD CONSTRAINT document_chunks_pkey PRIMARY KEY (id);

--
-- Name: document_page_index document_page_index_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.document_page_index
    ADD CONSTRAINT document_page_index_pkey PRIMARY KEY (id);

--
-- Name: document_strategies document_strategies_document_id_key; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.document_strategies
    ADD CONSTRAINT document_strategies_document_id_key UNIQUE (document_id);

--
-- Name: document_strategies document_strategies_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.document_strategies
    ADD CONSTRAINT document_strategies_pkey PRIMARY KEY (id);

--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);

--
-- Name: leads leads_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.leads
    ADD CONSTRAINT leads_pkey PRIMARY KEY (id);

--
-- Name: magic_links magic_links_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.magic_links
    ADD CONSTRAINT magic_links_pkey PRIMARY KEY (id);

--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);

--
-- Name: password_resets password_resets_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.password_resets
    ADD CONSTRAINT password_resets_pkey PRIMARY KEY (email);

--
-- Name: platform_settings platform_settings_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.platform_settings
    ADD CONSTRAINT platform_settings_pkey PRIMARY KEY (key);

--
-- Name: quick_answers quick_answers_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.quick_answers
    ADD CONSTRAINT quick_answers_pkey PRIMARY KEY (id);

--
-- Name: rate_limits rate_limits_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.rate_limits
    ADD CONSTRAINT rate_limits_pkey PRIMARY KEY (id);

--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);

--
-- Name: user_permissions user_permissions_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.user_permissions
    ADD CONSTRAINT user_permissions_pkey PRIMARY KEY (id);

--
-- Name: user_permissions user_permissions_user_id_permission_key; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.user_permissions
    ADD CONSTRAINT user_permissions_user_id_permission_key UNIQUE (user_id, permission);

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Name: idx_audit_logs_action; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON chatbot_schema.audit_logs USING btree (action);

--
-- Name: idx_audit_logs_admin_created; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_audit_logs_admin_created ON chatbot_schema.audit_logs USING btree (admin_id, created_at);

--
-- Name: idx_audit_logs_admin_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_audit_logs_admin_id ON chatbot_schema.audit_logs USING btree (admin_id);

--
-- Name: idx_audit_logs_created_at; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON chatbot_schema.audit_logs USING btree (created_at);

--
-- Name: idx_audit_logs_entity; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON chatbot_schema.audit_logs USING btree (entity_type, entity_id);

--
-- Name: idx_audit_logs_user_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON chatbot_schema.audit_logs USING btree (user_id);

--
-- Name: idx_chat_stats_admin_chatbot; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_chat_stats_admin_chatbot ON chatbot_schema.chat_stats USING btree (admin_id, chatbot_id);

--
-- Name: idx_chat_stats_admin_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_chat_stats_admin_id ON chatbot_schema.chat_stats USING btree (admin_id);

--
-- Name: idx_chat_stats_chatbot_created; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_chat_stats_chatbot_created ON chatbot_schema.chat_stats USING btree (chatbot_id, created_at);

--
-- Name: idx_chat_stats_date; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE UNIQUE INDEX idx_chat_stats_date ON chatbot_schema.chat_stats USING btree (chatbot_id, date);

--
-- Name: idx_chatbots_admin_created; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_chatbots_admin_created ON chatbot_schema.chatbots USING btree (admin_id, created_at);

--
-- Name: idx_chatbots_admin_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_chatbots_admin_id ON chatbot_schema.chatbots USING btree (admin_id);

--
-- Name: idx_chatbots_admin_status; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_chatbots_admin_status ON chatbot_schema.chatbots USING btree (admin_id, status);

--
-- Name: idx_chatbots_created_by; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_chatbots_created_by ON chatbot_schema.chatbots USING btree (created_by);

--
-- Name: idx_chatbots_widget_token; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE UNIQUE INDEX idx_chatbots_widget_token ON chatbot_schema.chatbots USING btree (widget_token);

--
-- Name: idx_chatbots_widget_token_idx; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_chatbots_widget_token_idx ON chatbot_schema.chatbots USING btree (widget_token);

--
-- Name: idx_conversations_admin_chatbot; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_conversations_admin_chatbot ON chatbot_schema.conversations USING btree (admin_id, chatbot_id);

--
-- Name: idx_conversations_admin_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_conversations_admin_id ON chatbot_schema.conversations USING btree (admin_id);

--
-- Name: idx_conversations_chatbot_created; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_conversations_chatbot_created ON chatbot_schema.conversations USING btree (chatbot_id, created_at);

--
-- Name: idx_conversations_chatbot_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_conversations_chatbot_id ON chatbot_schema.conversations USING btree (chatbot_id);

--
-- Name: idx_conversations_chatbot_last_msg; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_conversations_chatbot_last_msg ON chatbot_schema.conversations USING btree (chatbot_id, last_message_at);

--
-- Name: idx_conversations_visitor; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_conversations_visitor ON chatbot_schema.conversations USING btree (visitor_session_id);

--
-- Name: idx_doc_strategies_admin_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_doc_strategies_admin_id ON chatbot_schema.document_strategies USING btree (admin_id);

--
-- Name: idx_doc_strategies_chatbot_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_doc_strategies_chatbot_id ON chatbot_schema.document_strategies USING btree (chatbot_id);

--
-- Name: idx_doc_strategies_document_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_doc_strategies_document_id ON chatbot_schema.document_strategies USING btree (document_id);

--
-- Name: idx_doc_strategies_lookup; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_doc_strategies_lookup ON chatbot_schema.document_strategies USING btree (chatbot_id, original_name);

--
-- Name: idx_document_chunks_admin_chatbot; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_document_chunks_admin_chatbot ON chatbot_schema.document_chunks USING btree (admin_id, chatbot_id);

--
-- Name: idx_document_chunks_admin_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_document_chunks_admin_id ON chatbot_schema.document_chunks USING btree (admin_id);

--
-- Name: idx_document_chunks_chatbot_doc; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_document_chunks_chatbot_doc ON chatbot_schema.document_chunks USING btree (chatbot_id, document_id);

--
-- Name: idx_document_chunks_chatbot_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_document_chunks_chatbot_id ON chatbot_schema.document_chunks USING btree (chatbot_id);

--
-- Name: idx_document_chunks_document_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_document_chunks_document_id ON chatbot_schema.document_chunks USING btree (document_id);

--
-- Name: idx_document_chunks_embedding; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_document_chunks_embedding ON chatbot_schema.document_chunks USING ivfflat (embedding chatbot_schema.vector_cosine_ops) WITH (lists='100');

--
-- Name: idx_documents_admin_chatbot; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_documents_admin_chatbot ON chatbot_schema.documents USING btree (admin_id, chatbot_id);

--
-- Name: idx_documents_admin_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_documents_admin_id ON chatbot_schema.documents USING btree (admin_id);

--
-- Name: idx_documents_chatbot_created; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_documents_chatbot_created ON chatbot_schema.documents USING btree (chatbot_id, created_at);

--
-- Name: idx_documents_chatbot_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_documents_chatbot_id ON chatbot_schema.documents USING btree (chatbot_id);

--
-- Name: idx_documents_status; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_documents_status ON chatbot_schema.documents USING btree (status);

--
-- Name: idx_documents_uploaded_by; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_documents_uploaded_by ON chatbot_schema.documents USING btree (uploaded_by);

--
-- Name: idx_leads_admin; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_leads_admin ON chatbot_schema.leads USING btree (admin_id);

--
-- Name: idx_leads_chatbot; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_leads_chatbot ON chatbot_schema.leads USING btree (chatbot_id);

--
-- Name: idx_leads_conversation; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_leads_conversation ON chatbot_schema.leads USING btree (conversation_id);

--
-- Name: idx_magic_links_admin; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_magic_links_admin ON chatbot_schema.magic_links USING btree (admin_id);

--
-- Name: idx_magic_links_email; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_magic_links_email ON chatbot_schema.magic_links USING btree (email);

--
-- Name: idx_magic_links_expires; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_magic_links_expires ON chatbot_schema.magic_links USING btree (expires_at);

--
-- Name: idx_magic_links_token; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_magic_links_token ON chatbot_schema.magic_links USING btree (token);

--
-- Name: idx_messages_admin_chatbot; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_messages_admin_chatbot ON chatbot_schema.messages USING btree (admin_id, chatbot_id);

--
-- Name: idx_messages_admin_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_messages_admin_id ON chatbot_schema.messages USING btree (admin_id);

--
-- Name: idx_messages_chatbot_created; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_messages_chatbot_created ON chatbot_schema.messages USING btree (chatbot_id, created_at);

--
-- Name: idx_messages_chatbot_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_messages_chatbot_id ON chatbot_schema.messages USING btree (chatbot_id);

--
-- Name: idx_messages_conversation_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON chatbot_schema.messages USING btree (conversation_id);

--
-- Name: idx_messages_visitor; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_messages_visitor ON chatbot_schema.messages USING btree (visitor_session_id);

--
-- Name: idx_page_index_admin_chatbot; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_page_index_admin_chatbot ON chatbot_schema.document_page_index USING btree (admin_id, chatbot_id);

--
-- Name: idx_page_index_admin_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_page_index_admin_id ON chatbot_schema.document_page_index USING btree (admin_id);

--
-- Name: idx_page_index_chatbot_doc; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_page_index_chatbot_doc ON chatbot_schema.document_page_index USING btree (chatbot_id, document_id);

--
-- Name: idx_page_index_chatbot_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_page_index_chatbot_id ON chatbot_schema.document_page_index USING btree (chatbot_id);

--
-- Name: idx_page_index_document_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_page_index_document_id ON chatbot_schema.document_page_index USING btree (document_id);

--
-- Name: idx_page_index_parent_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_page_index_parent_id ON chatbot_schema.document_page_index USING btree (parent_id);

--
-- Name: idx_password_resets_expires; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_password_resets_expires ON chatbot_schema.password_resets USING btree (expires_at);

--
-- Name: idx_password_resets_token; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_password_resets_token ON chatbot_schema.password_resets USING btree (token);

--
-- Name: idx_quick_answers_admin_chatbot; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_quick_answers_admin_chatbot ON chatbot_schema.quick_answers USING btree (admin_id, chatbot_id);

--
-- Name: idx_quick_answers_admin_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_quick_answers_admin_id ON chatbot_schema.quick_answers USING btree (admin_id);

--
-- Name: idx_quick_answers_chatbot_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_quick_answers_chatbot_id ON chatbot_schema.quick_answers USING btree (chatbot_id);

--
-- Name: idx_rate_limits_key; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_rate_limits_key ON chatbot_schema.rate_limits USING btree (key);

--
-- Name: idx_sessions_admin_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_sessions_admin_id ON chatbot_schema.sessions USING btree (admin_id);

--
-- Name: idx_sessions_last_activity; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_sessions_last_activity ON chatbot_schema.sessions USING btree (last_activity);

--
-- Name: idx_sessions_user_id; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON chatbot_schema.sessions USING btree (user_id);


-- Name: idx_users_admin_role; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_users_admin_role ON chatbot_schema.users USING btree (admin_id, role);

--
-- Name: idx_users_company_name; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_users_company_name ON chatbot_schema.users USING btree (company_name);

--
-- Name: idx_users_email; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE UNIQUE INDEX idx_users_email ON chatbot_schema.users USING btree (email);

--
-- Name: idx_users_is_active; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_users_is_active ON chatbot_schema.users USING btree (is_active);

--
-- Name: idx_users_role; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE INDEX IF NOT EXISTS idx_users_role ON chatbot_schema.users USING btree (role);

--
-- Name: idx_users_slug; Type: INDEX; Schema: chatbot_schema; Owner: -
--

CREATE UNIQUE INDEX idx_users_slug ON chatbot_schema.users USING btree (slug);

--
-- Name: audit_logs audit_logs_admin_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.audit_logs
    ADD CONSTRAINT audit_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES chatbot_schema.users(id) ON DELETE CASCADE;

--
-- Name: audit_logs audit_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.audit_logs
    ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES chatbot_schema.users(id) ON DELETE SET NULL;

--
-- Name: chat_stats chat_stats_admin_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.chat_stats
    ADD CONSTRAINT chat_stats_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES chatbot_schema.users(id) ON DELETE CASCADE;

--
-- Name: chat_stats chat_stats_chatbot_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.chat_stats
    ADD CONSTRAINT chat_stats_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES chatbot_schema.chatbots(id) ON DELETE CASCADE;

--
-- Name: chatbots chatbots_admin_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.chatbots
    ADD CONSTRAINT chatbots_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES chatbot_schema.users(id) ON DELETE CASCADE;

--
-- Name: chatbots chatbots_created_by_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.chatbots
    ADD CONSTRAINT chatbots_created_by_fkey FOREIGN KEY (created_by) REFERENCES chatbot_schema.users(id);

--
-- Name: conversations conversations_admin_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.conversations
    ADD CONSTRAINT conversations_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES chatbot_schema.users(id) ON DELETE CASCADE;

--
-- Name: conversations conversations_chatbot_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.conversations
    ADD CONSTRAINT conversations_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES chatbot_schema.chatbots(id) ON DELETE CASCADE;

--
-- Name: document_chunks document_chunks_admin_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.document_chunks
    ADD CONSTRAINT document_chunks_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES chatbot_schema.users(id) ON DELETE CASCADE;

--
-- Name: document_chunks document_chunks_chatbot_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.document_chunks
    ADD CONSTRAINT document_chunks_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES chatbot_schema.chatbots(id) ON DELETE CASCADE;

--
-- Name: document_chunks document_chunks_document_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.document_chunks
    ADD CONSTRAINT document_chunks_document_id_fkey FOREIGN KEY (document_id) REFERENCES chatbot_schema.documents(id) ON DELETE CASCADE;

--
-- Name: document_page_index document_page_index_admin_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.document_page_index
    ADD CONSTRAINT document_page_index_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES chatbot_schema.users(id) ON DELETE CASCADE;

--
-- Name: document_page_index document_page_index_chatbot_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.document_page_index
    ADD CONSTRAINT document_page_index_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES chatbot_schema.chatbots(id) ON DELETE CASCADE;

--
-- Name: document_page_index document_page_index_document_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.document_page_index
    ADD CONSTRAINT document_page_index_document_id_fkey FOREIGN KEY (document_id) REFERENCES chatbot_schema.documents(id) ON DELETE CASCADE;

--
-- Name: document_page_index document_page_index_parent_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.document_page_index
    ADD CONSTRAINT document_page_index_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES chatbot_schema.document_page_index(id) ON DELETE CASCADE;

--
-- Name: document_strategies document_strategies_admin_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.document_strategies
    ADD CONSTRAINT document_strategies_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES chatbot_schema.users(id) ON DELETE CASCADE;

--
-- Name: document_strategies document_strategies_chatbot_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.document_strategies
    ADD CONSTRAINT document_strategies_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES chatbot_schema.chatbots(id) ON DELETE CASCADE;

--
-- Name: document_strategies document_strategies_document_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.document_strategies
    ADD CONSTRAINT document_strategies_document_id_fkey FOREIGN KEY (document_id) REFERENCES chatbot_schema.documents(id) ON DELETE CASCADE;

--
-- Name: documents documents_admin_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.documents
    ADD CONSTRAINT documents_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES chatbot_schema.users(id) ON DELETE CASCADE;

--
-- Name: documents documents_chatbot_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.documents
    ADD CONSTRAINT documents_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES chatbot_schema.chatbots(id) ON DELETE CASCADE;

--
-- Name: documents documents_uploaded_by_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.documents
    ADD CONSTRAINT documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES chatbot_schema.users(id);

--
-- Name: users fk_users_admin; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.users
    ADD CONSTRAINT fk_users_admin FOREIGN KEY (admin_id) REFERENCES chatbot_schema.users(id) ON DELETE CASCADE DEFERRABLE;

--
-- Name: leads leads_admin_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.leads
    ADD CONSTRAINT leads_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES chatbot_schema.users(id) ON DELETE CASCADE;

--
-- Name: leads leads_chatbot_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.leads
    ADD CONSTRAINT leads_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES chatbot_schema.chatbots(id) ON DELETE CASCADE;

--
-- Name: magic_links magic_links_admin_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.magic_links
    ADD CONSTRAINT magic_links_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES chatbot_schema.users(id) ON DELETE CASCADE;

--
-- Name: messages messages_admin_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.messages
    ADD CONSTRAINT messages_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES chatbot_schema.users(id) ON DELETE CASCADE;

--
-- Name: messages messages_chatbot_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.messages
    ADD CONSTRAINT messages_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES chatbot_schema.chatbots(id) ON DELETE CASCADE;

--
-- Name: messages messages_conversation_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.messages
    ADD CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES chatbot_schema.conversations(id) ON DELETE CASCADE;

--
-- Name: quick_answers quick_answers_admin_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.quick_answers
    ADD CONSTRAINT quick_answers_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES chatbot_schema.users(id) ON DELETE CASCADE;

--
-- Name: quick_answers quick_answers_chatbot_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.quick_answers
    ADD CONSTRAINT quick_answers_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES chatbot_schema.chatbots(id) ON DELETE CASCADE;

--
-- Name: sessions sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES chatbot_schema.users(id) ON DELETE CASCADE;

--
-- Name: user_permissions user_permissions_user_id_fkey; Type: FK CONSTRAINT; Schema: chatbot_schema; Owner: -
--

ALTER TABLE ONLY chatbot_schema.user_permissions
    ADD CONSTRAINT user_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES chatbot_schema.users(id) ON DELETE CASCADE;

--
-- Name: audit_logs; Type: ROW SECURITY; Schema: chatbot_schema; Owner: -
--

ALTER TABLE chatbot_schema.audit_logs ENABLE ROW LEVEL SECURITY;

--
-- Name: chat_stats; Type: ROW SECURITY; Schema: chatbot_schema; Owner: -
--

ALTER TABLE chatbot_schema.chat_stats ENABLE ROW LEVEL SECURITY;

--
-- Name: chatbots; Type: ROW SECURITY; Schema: chatbot_schema; Owner: -
--

ALTER TABLE chatbot_schema.chatbots ENABLE ROW LEVEL SECURITY;

--
-- Name: conversations; Type: ROW SECURITY; Schema: chatbot_schema; Owner: -
--

ALTER TABLE chatbot_schema.conversations ENABLE ROW LEVEL SECURITY;

--
-- Name: document_chunks; Type: ROW SECURITY; Schema: chatbot_schema; Owner: -
--

ALTER TABLE chatbot_schema.document_chunks ENABLE ROW LEVEL SECURITY;

--
-- Name: document_page_index; Type: ROW SECURITY; Schema: chatbot_schema; Owner: -
--

ALTER TABLE chatbot_schema.document_page_index ENABLE ROW LEVEL SECURITY;

--
-- Name: document_strategies; Type: ROW SECURITY; Schema: chatbot_schema; Owner: -
--

ALTER TABLE chatbot_schema.document_strategies ENABLE ROW LEVEL SECURITY;

--
-- Name: documents; Type: ROW SECURITY; Schema: chatbot_schema; Owner: -
--

ALTER TABLE chatbot_schema.documents ENABLE ROW LEVEL SECURITY;

--
-- Name: leads; Type: ROW SECURITY; Schema: chatbot_schema; Owner: -
--

ALTER TABLE chatbot_schema.leads ENABLE ROW LEVEL SECURITY;

--
-- Name: magic_links; Type: ROW SECURITY; Schema: chatbot_schema; Owner: -
--

ALTER TABLE chatbot_schema.magic_links ENABLE ROW LEVEL SECURITY;

--
-- Name: messages; Type: ROW SECURITY; Schema: chatbot_schema; Owner: -
--

ALTER TABLE chatbot_schema.messages ENABLE ROW LEVEL SECURITY;

--
-- Name: quick_answers; Type: ROW SECURITY; Schema: chatbot_schema; Owner: -
--

ALTER TABLE chatbot_schema.quick_answers ENABLE ROW LEVEL SECURITY;

--
-- Name: audit_logs rls_audit_logs_insert; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_audit_logs_insert ON chatbot_schema.audit_logs FOR INSERT WITH CHECK (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: audit_logs rls_audit_logs_select; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_audit_logs_select ON chatbot_schema.audit_logs FOR SELECT USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: chat_stats rls_chat_stats_insert; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_chat_stats_insert ON chatbot_schema.chat_stats FOR INSERT WITH CHECK (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: chat_stats rls_chat_stats_select; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_chat_stats_select ON chatbot_schema.chat_stats FOR SELECT USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: chat_stats rls_chat_stats_update; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_chat_stats_update ON chatbot_schema.chat_stats FOR UPDATE USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: chatbots rls_chatbots_delete; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_chatbots_delete ON chatbot_schema.chatbots FOR DELETE USING (((admin_id = chatbot_schema.current_admin_id()) OR (created_by = chatbot_schema.current_admin_id())));

--
-- Name: chatbots rls_chatbots_insert; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_chatbots_insert ON chatbot_schema.chatbots FOR INSERT WITH CHECK ((admin_id = chatbot_schema.current_admin_id()));

--
-- Name: chatbots rls_chatbots_select; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_chatbots_select ON chatbot_schema.chatbots FOR SELECT USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id()) OR (created_by = chatbot_schema.current_admin_id())));

--
-- Name: chatbots rls_chatbots_update; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_chatbots_update ON chatbot_schema.chatbots FOR UPDATE USING (((admin_id = chatbot_schema.current_admin_id()) OR (created_by = chatbot_schema.current_admin_id())));

--
-- Name: conversations rls_conversations_delete; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_conversations_delete ON chatbot_schema.conversations FOR DELETE USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: conversations rls_conversations_insert; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_conversations_insert ON chatbot_schema.conversations FOR INSERT WITH CHECK (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: conversations rls_conversations_select; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_conversations_select ON chatbot_schema.conversations FOR SELECT USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: conversations rls_conversations_update; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_conversations_update ON chatbot_schema.conversations FOR UPDATE USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: document_strategies rls_doc_strategies_delete; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_doc_strategies_delete ON chatbot_schema.document_strategies FOR DELETE USING ((admin_id = chatbot_schema.current_admin_id()));

--
-- Name: document_strategies rls_doc_strategies_insert; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_doc_strategies_insert ON chatbot_schema.document_strategies FOR INSERT WITH CHECK ((admin_id = chatbot_schema.current_admin_id()));

--
-- Name: document_strategies rls_doc_strategies_select; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_doc_strategies_select ON chatbot_schema.document_strategies FOR SELECT USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: document_strategies rls_doc_strategies_update; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_doc_strategies_update ON chatbot_schema.document_strategies FOR UPDATE USING ((admin_id = chatbot_schema.current_admin_id()));

--
-- Name: document_chunks rls_document_chunks_delete; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_document_chunks_delete ON chatbot_schema.document_chunks FOR DELETE USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: document_chunks rls_document_chunks_insert; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_document_chunks_insert ON chatbot_schema.document_chunks FOR INSERT WITH CHECK (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: document_chunks rls_document_chunks_select; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_document_chunks_select ON chatbot_schema.document_chunks FOR SELECT USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: documents rls_documents_delete; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_documents_delete ON chatbot_schema.documents FOR DELETE USING ((admin_id = chatbot_schema.current_admin_id()));

--
-- Name: documents rls_documents_insert; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_documents_insert ON chatbot_schema.documents FOR INSERT WITH CHECK ((admin_id = chatbot_schema.current_admin_id()));

--
-- Name: documents rls_documents_select; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_documents_select ON chatbot_schema.documents FOR SELECT USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: documents rls_documents_update; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_documents_update ON chatbot_schema.documents FOR UPDATE USING ((admin_id = chatbot_schema.current_admin_id()));

--
-- Name: leads rls_leads_delete; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_leads_delete ON chatbot_schema.leads FOR DELETE USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: leads rls_leads_insert; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_leads_insert ON chatbot_schema.leads FOR INSERT WITH CHECK (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: leads rls_leads_select; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_leads_select ON chatbot_schema.leads FOR SELECT USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: leads rls_leads_update; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_leads_update ON chatbot_schema.leads FOR UPDATE USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: magic_links rls_magic_links_delete; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_magic_links_delete ON chatbot_schema.magic_links FOR DELETE USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: magic_links rls_magic_links_insert; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_magic_links_insert ON chatbot_schema.magic_links FOR INSERT WITH CHECK (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: magic_links rls_magic_links_select; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_magic_links_select ON chatbot_schema.magic_links FOR SELECT USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: magic_links rls_magic_links_update; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_magic_links_update ON chatbot_schema.magic_links FOR UPDATE USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: messages rls_messages_delete; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_messages_delete ON chatbot_schema.messages FOR DELETE USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: messages rls_messages_insert; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_messages_insert ON chatbot_schema.messages FOR INSERT WITH CHECK (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: messages rls_messages_select; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_messages_select ON chatbot_schema.messages FOR SELECT USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: document_page_index rls_page_index_delete; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_page_index_delete ON chatbot_schema.document_page_index FOR DELETE USING ((admin_id = chatbot_schema.current_admin_id()));

--
-- Name: document_page_index rls_page_index_insert; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_page_index_insert ON chatbot_schema.document_page_index FOR INSERT WITH CHECK ((admin_id = chatbot_schema.current_admin_id()));

--
-- Name: document_page_index rls_page_index_select; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_page_index_select ON chatbot_schema.document_page_index FOR SELECT USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: document_page_index rls_page_index_update; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_page_index_update ON chatbot_schema.document_page_index FOR UPDATE USING ((admin_id = chatbot_schema.current_admin_id()));

--
-- Name: quick_answers rls_quick_answers_delete; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_quick_answers_delete ON chatbot_schema.quick_answers FOR DELETE USING ((admin_id = chatbot_schema.current_admin_id()));

--
-- Name: quick_answers rls_quick_answers_insert; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_quick_answers_insert ON chatbot_schema.quick_answers FOR INSERT WITH CHECK ((admin_id = chatbot_schema.current_admin_id()));

--
-- Name: quick_answers rls_quick_answers_select; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_quick_answers_select ON chatbot_schema.quick_answers FOR SELECT USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: quick_answers rls_quick_answers_update; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_quick_answers_update ON chatbot_schema.quick_answers FOR UPDATE USING ((admin_id = chatbot_schema.current_admin_id()));

--
-- Name: sessions rls_sessions_delete; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_sessions_delete ON chatbot_schema.sessions FOR DELETE USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: sessions rls_sessions_insert; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_sessions_insert ON chatbot_schema.sessions FOR INSERT WITH CHECK (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: sessions rls_sessions_select; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_sessions_select ON chatbot_schema.sessions FOR SELECT USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: sessions rls_sessions_update; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_sessions_update ON chatbot_schema.sessions FOR UPDATE USING (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: user_permissions rls_user_permissions_delete; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_user_permissions_delete ON chatbot_schema.user_permissions FOR DELETE USING (((chatbot_schema.current_admin_id() IS NULL) OR (user_id IN ( SELECT users.id
   FROM chatbot_schema.users
  WHERE (users.admin_id = chatbot_schema.current_admin_id())
UNION
 SELECT chatbot_schema.current_admin_id() AS current_admin_id))));

--
-- Name: user_permissions rls_user_permissions_insert; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_user_permissions_insert ON chatbot_schema.user_permissions FOR INSERT WITH CHECK (((chatbot_schema.current_admin_id() IS NULL) OR (user_id IN ( SELECT users.id
   FROM chatbot_schema.users
  WHERE (users.admin_id = chatbot_schema.current_admin_id())
UNION
 SELECT chatbot_schema.current_admin_id() AS current_admin_id))));

--
-- Name: user_permissions rls_user_permissions_select; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_user_permissions_select ON chatbot_schema.user_permissions FOR SELECT USING (((chatbot_schema.current_admin_id() IS NULL) OR (user_id IN ( SELECT users.id
   FROM chatbot_schema.users
  WHERE (users.admin_id = chatbot_schema.current_admin_id())
UNION
 SELECT chatbot_schema.current_admin_id() AS current_admin_id))));

--
-- Name: user_permissions rls_user_permissions_update; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_user_permissions_update ON chatbot_schema.user_permissions FOR UPDATE USING (((chatbot_schema.current_admin_id() IS NULL) OR (user_id IN ( SELECT users.id
   FROM chatbot_schema.users
  WHERE (users.admin_id = chatbot_schema.current_admin_id())
UNION
 SELECT chatbot_schema.current_admin_id() AS current_admin_id))));

--
-- Name: users rls_users_delete; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_users_delete ON chatbot_schema.users FOR DELETE USING (((chatbot_schema.current_admin_id() IS NULL) OR ((admin_id = chatbot_schema.current_admin_id()) AND ((role)::text = 'user'::text) AND (id <> chatbot_schema.current_admin_id()))));

--
-- Name: users rls_users_insert; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_users_insert ON chatbot_schema.users FOR INSERT WITH CHECK (((chatbot_schema.current_admin_id() IS NULL) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: users rls_users_select; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_users_select ON chatbot_schema.users FOR SELECT USING (((chatbot_schema.current_admin_id() IS NULL) OR (id = chatbot_schema.current_admin_id()) OR (admin_id = chatbot_schema.current_admin_id())));

--
-- Name: users rls_users_update; Type: POLICY; Schema: chatbot_schema; Owner: -
--

CREATE POLICY rls_users_update ON chatbot_schema.users FOR UPDATE USING (((chatbot_schema.current_admin_id() IS NULL) OR (id = chatbot_schema.current_admin_id()) OR ((admin_id = chatbot_schema.current_admin_id()) AND ((role)::text = 'user'::text)))) WITH CHECK (((chatbot_schema.current_admin_id() IS NULL) OR (id = chatbot_schema.current_admin_id()) OR ((admin_id = chatbot_schema.current_admin_id()) AND ((role)::text = 'user'::text))));

--
-- Name: sessions; Type: ROW SECURITY; Schema: chatbot_schema; Owner: -
--

ALTER TABLE chatbot_schema.sessions ENABLE ROW LEVEL SECURITY;

--
-- Name: user_permissions; Type: ROW SECURITY; Schema: chatbot_schema; Owner: -
--

ALTER TABLE chatbot_schema.user_permissions ENABLE ROW LEVEL SECURITY;

--
-- Name: users; Type: ROW SECURITY; Schema: chatbot_schema; Owner: -
--

ALTER TABLE chatbot_schema.users ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--
