<?php

/**
 * Copyright (c) 2026 Online Tech Support, LLC
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

declare(strict_types=1);

namespace App\Auth;

use PDO;

/**
 * Simple per-IP rate limiter backed by the application database.
 *
 * Limits login attempts per IP address to prevent brute-force attacks.
 * Uses a dedicated rate_limits table with automatic cleanup of expired rows.
 */
class RateLimiter
{
    private const TABLE = 'rate_limits';

    /**
     * Check if the given IP has exceeded the rate limit.
     *
     * @param string $ip       Client IP address.
     * @param int    $maxAttempts  Max allowed attempts in the window.
     * @param int    $windowSec    Time window in seconds.
     * @return bool True if allowed, false if rate-limited.
     */
    public static function check(string $ip, int $maxAttempts = 10, int $windowSec = 300, string $keyPrefix = 'login:'): bool
    {
        $db = self::db();
        $key = $keyPrefix . $ip;
        $cutoff = date('Y-m-d H:i:s', time() - $windowSec);

        // Prune stale rows for this key
        $stmt = $db->prepare(
            'DELETE FROM ' . self::TABLE . ' WHERE key = :key AND created_at < :cutoff'
        );
        $stmt->execute([':key' => $key, ':cutoff' => $cutoff]);

        // Count attempts in the window
        $stmt = $db->prepare(
            'SELECT COUNT(*) AS cnt FROM ' . self::TABLE . ' WHERE key = :key'
        );
        $stmt->execute([':key' => $key]);
        $row = $stmt->fetch(\PDO::FETCH_ASSOC);

        return ($row['cnt'] ?? 0) < $maxAttempts;
    }

    /**
     * Record an attempt for the given IP.
     */
    public static function record(string $ip, string $keyPrefix = 'login:'): void
    {
        $db = self::db();
        $key = $keyPrefix . $ip;

        $stmt = $db->prepare(
            'INSERT INTO ' . self::TABLE . ' (key, created_at) VALUES (:key, :now)'
        );
        $stmt->execute([
            ':key' => $key,
            ':now' => date('Y-m-d H:i:s'),
        ]);
    }

    /**
     * Clear all rate-limit entries for the given IP (on successful login).
     */
    public static function clear(string $ip, string $keyPrefix = 'login:'): void
    {
        $db = self::db();
        $key = $keyPrefix . $ip;

        $stmt = $db->prepare('DELETE FROM ' . self::TABLE . ' WHERE key = :key');
        $stmt->execute([':key' => $key]);
    }

    private static ?bool $_tableChecked = null;

    /**
     * Get the shared database connection via the app's global getDb().
     */
    private static function db(): \PDO
    {
        $pdo = \getDb();
        if (self::$_tableChecked === null) {
            // Bypass db() during table creation to avoid recursion
            self::$_tableChecked = true;
            self::ensureTableInternal($pdo);
        }
        return $pdo;
    }

    /**
     * Create the rate_limits table if it doesn't exist.
     */
    public static function ensureTable(): void
    {
        $pdo = \getDb();
        if (self::$_tableChecked === null) {
            self::$_tableChecked = true;
            self::ensureTableInternal($pdo);
        }
    }

    /**
     * Internal: create the table using a given PDO connection.
     */
    private static function ensureTableInternal(\PDO $db): void
    {
        // Table and index are created by the migration (001_initial.sql);
        // IF NOT EXISTS makes re-runs safe. The app user may not own the
        // table (RLS ownership model), so skip index DDL — it already
        // exists from the migration. Column is 'key' to match migration.
        $db->exec(
            'CREATE TABLE IF NOT EXISTS ' . self::TABLE . ' (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(255) NOT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )'
        );
    }
}
